### ISSUE TITLE
Vivaldi mouse gestures

### ISSUE THREAD

**Issue by jesus2099** [ultimate-enable-right-click/help#4]
With this extension on, Vivaldi mouse gestures will make the contextual menu appear.
I understand why it now appears.
The extension should detect mouse gestures and let them block the click event.
But I don't know if it's possible.

Example of mouse gestures, it's always keep right click and:

| Gesture | Over the page | Over a link |
|---------|---------------|-------------|
| down    | new tab       | open link in new tab |
| down, up | duplicate tab (my custom rule) | open link in background tab |

It's not very bad that the contextual menu appears but it's not very clean.

**Comment by jesus2099** [comment]
I need to find a repro because it does not happen now.
I think I was on GitHub.com where there _Enable right click_ slider was on the left (because they are not blocked on GH).
But now it does not happen!?

**Comment by ultimate-enable-right-click** [comment]
Thanks, but I can't reproduce too. Please re-open if it happens again.
