### ISSUE TITLE
Toggle switch is implemented backwards

### ISSUE THREAD

**Issue by daylightbrightledlight** [ultimate-enable-right-click/help#6]
Hi, I appreciate your extension.

I just want to note that the CSS on/off toggle switch on your extension's ​Per-site settings page is implemented backwards. I think the standard is to enable when the toggle is on the right, and disable when the toggle is on the left. A quick search of "CSS toggle" will show examples.

**Comment by ultimate-enable-right-click** [comment]
According to your description of "standard", the extension follows the standard. The extension's features are enabled when its corresponding toggle is on the right.
